export const ROUTES = {
  HOME: "/",
  CATALOG: "/catalog",
  ADD_PROJECT: "/add-project",
  BUSINESS_OFFICE: "/business-office",
  BUSINESS_OFFICE_APPLY: "/business-office/apply",
  BUSINESS_OFFICE_REGISTER: "/business-office/register",
  BUSINESS_OFFICE_SPLITS: "/business-office/splits",
  BUSINESS_OFFICE_PROPOSE_PROJECT: "/business-office/propose-project",
  BUSINESS_OFFICE_PURCHASE: "/business-office/purchase",
  BUSINESS_OFFICE_TRANSACTIONS: "/business-office/transactions",
  SUBSCRIPTION: "/subscription",
  LEASE_TO_OWN: "/lease-to-own",
  PROPOSE_PROJECT: "/propose-project",
  PROJECT_RECEIVED: "/project-received",
  ASSOCIATE_STATUS: "/associate-status",
  ADMIN: "/admin",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_LEADS: "/admin/leads",
  ADMIN_LEADS_SIMULATION: "/admin/leads-simulation",
  ADMIN_PRICING: "/admin/pricing",
  ADMIN_USERS: "/admin/users",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_FAST_CODES: "/admin/fast-codes",
  ADMIN_DEALS: "/admin/deals",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_APPLICATIONS: "/admin/applications",
  ADMIN_PROJECTS: "/admin/projects",
  GLASSHOUSE: "/glasshouse",
  TALISHOUSE: "/talishouse",
  TALISTOWNS: "/talistowns",
  DEALERS: "/dealers",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  FIND_YOUR_HOME: "/find-your-home",
  MATCH_RESULTS: "/match-results",
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RouteValue = (typeof ROUTES)[RouteKey];
