export const ROUTES = {
  HOME: "/",
  CATALOG: "/catalogue",
  ADD_PROJECT: "/add-project",
  BUSINESS_OFFICE: "/business-office",
  BUSINESS_OFFICE_APPLY: "/business-office/apply",
  BUSINESS_OFFICE_REGISTER: "/business-office/register",
  BUSINESS_OFFICE_SPLITS: "/business-office/splits",
  BUSINESS_OFFICE_PROPOSE_PROJECT: "/business-office/propose-project",
  BUSINESS_OFFICE_PURCHASE: "/business-office/purchase",
  BUSINESS_OFFICE_TRANSACTIONS: "/business-office/transactions",
  SUBSCRIPTION: "/subscription",
  LEASE_TO_OWN: "/lease-to-own",
  PROPOSE_PROJECT: "/propose-project",
  PROJECT_RECEIVED: "/project-received",
  ASSOCIATE_STATUS: "/associate-status",
  ADMIN: "/admin",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_LEADS: "/admin/leads",
  ADMIN_LEADS_SIMULATION: "/admin/leads-simulation",
  ADMIN_PRICING: "/admin/pricing",
  ADMIN_USERS: "/admin/users",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_FAST_CODES: "/admin/fast-codes",
  ADMIN_DEALS: "/admin/deals",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_APPLICATIONS: "/admin/applications",
  ADMIN_PROJECTS: "/admin/projects",
  GLASSHOUSE: "/glasshouse",
  TALISHOUSE: "/talishouse",
  TALISTOWNS: "/talistowns",
  DEALERS: "/dealers",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  FIND_YOUR_MARKET: "/find-your-market",
  MATCH_RESULTS: "/match-results",
  TALISMAPS: "/talismaps",
  TALISMAPS_DASHBOARD: "/talismaps/dashboard",
  TALISMAPS_EDITOR: "/talismaps/editor",
  TALISMAPS_SETTINGS: "/talismaps/settings",
  TALISMAPS_ADMIN: "/admin/talismaps",
  TALISBOOKS: "/talisbooks",
  TALISBOOKS_DASHBOARD: "/talisbooks/dashboard",
  TALISBOOKS_LIBRARY: "/talisbooks/library",
  TALISBOOKS_EDITOR: "/talisbooks/editor",
  TALISBOOKS_VIEWER: "/talisbooks/viewer",
  TALISBOOKS_SETTINGS: "/talisbooks/settings",
  TALISBOOKS_ADMIN: "/admin/talisbooks",
  TALISBOOKS_ADMIN_CENTERFOLDS: "/admin/talisbooks/centerfolds",
  TALISBOOKS_CLIENT_BOOKS: "/client/books",
  TALISTV: "/talistv",
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RouteValue = (typeof ROUTES)[RouteKey];
