import type { Database } from "@/lib/database.types";
import { uploadBuildMapsiteAsset } from "@/lib/build-mapsite-upload";
import { sendBuildRequestReceived } from "@/lib/email";
import { autoGenerateDraftTalisBook } from "@/lib/talisbooks/auto-draft-ebook";
import { getSupabaseAdmin, isSupabaseAdminConfigured } from "@/lib/supabaseAdmin";

const RAHUL_ASSIGNEE = "Rahul";

export type RahulEbookAssistInput = {
  fastCode?: string | null;
  mapsiteId?: string | null;
  accountType?: string | null;
  requestId?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  phone?: string | null;
  propertyTitle: string;
  description: string;
  location: string;
  agentPhoto?: File | null;
  logo?: File | null;
  images: File[];
};

export type RahulEbookAssistResult =
  | {
      success: true;
      requestId: string;
      fastCode: string | null;
      previewUrl?: string;
      bookSlug?: string;
    }
  | { success: false; error: string };

/**
 * Create or update a Build Request for Rahul-assisted TEB™ production.
 * Does not change submitBuildRequest; uses the same tables/assets.
 */
export async function submitRahulEbookAssistRequest(
  input: RahulEbookAssistInput
): Promise<RahulEbookAssistResult> {
  const propertyTitle = input.propertyTitle.trim();
  const description = input.description.trim();
  const location = input.location.trim();

  if (!propertyTitle) {
    return { success: false, error: "Property title is required." };
  }
  if (!description) {
    return { success: false, error: "Property description is required." };
  }
  if (!location) {
    return { success: false, error: "Property location is required." };
  }
  if (!input.images.length) {
    return { success: false, error: "Upload at least one property image (1–22)." };
  }
  if (!isSupabaseAdminConfigured()) {
    return { success: false, error: "Database is not configured." };
  }

  const supabase = getSupabaseAdmin();
  const existingId = input.requestId?.trim() || null;

  let existing: {
    id: string;
    first_name: string | null;
    last_name: string | null;
    email: string | null;
    phone: string | null;
    requested_fast_code: string | null;
    requested_account_type: string | null;
    account_type: string | null;
    linked_mapsite_id: string | null;
    gallery_images: string[] | null;
    logo: string | null;
  } | null = null;

  if (existingId) {
    const { data } = await supabase
      .from("build_requests")
      .select(
        "id, first_name, last_name, email, phone, requested_fast_code, requested_account_type, account_type, linked_mapsite_id, gallery_images, logo"
      )
      .eq("id", existingId)
      .maybeSingle();
    existing = data;
  }

  const firstName =
    input.firstName?.trim() || existing?.first_name?.trim() || "Client";
  const lastName =
    input.lastName?.trim() || existing?.last_name?.trim() || "MapSite";
  const email =
    input.email?.trim().toLowerCase() || existing?.email?.trim().toLowerCase() || "";
  const phone = input.phone?.trim() || existing?.phone?.trim() || "";

  if (!email) {
    return {
      success: false,
      error: "Email is required so we can notify you when Rahul finishes your E-Book.",
    };
  }

  const requestId = existing?.id || crypto.randomUUID();
  const fastCode =
    input.fastCode?.trim().toLowerCase() ||
    existing?.requested_fast_code?.trim().toLowerCase() ||
    null;
  const accountType =
    input.accountType?.trim() ||
    existing?.requested_account_type ||
    existing?.account_type ||
    "root";
  const mapsiteId =
    input.mapsiteId?.trim() || existing?.linked_mapsite_id || null;

  const agentPhotoUrl = input.agentPhoto
    ? await uploadBuildMapsiteAsset(requestId, "picture", input.agentPhoto)
    : null;
  const logoUrl = input.logo
    ? await uploadBuildMapsiteAsset(requestId, "logo", input.logo)
    : existing?.logo || null;

  const galleryUrls: string[] = [];
  for (let i = 0; i < Math.min(input.images.length, 22); i += 1) {
    const file = input.images[i]!;
    const url = await uploadBuildMapsiteAsset(requestId, `tebPicture_${i}`, file);
    if (url) galleryUrls.push(url);
  }

  if (galleryUrls.length === 0) {
    return {
      success: false,
      error: "Could not upload property images. Try again with JPG or PNG files.",
    };
  }

  const now = new Date().toISOString();
  const notes = [
    "ebook:rahul",
    "Assigned to Rahul for assisted TalisBooks™ / TEB™ production.",
    `Property: ${propertyTitle}`,
    `Location: ${location}`,
  ].join("\n");

  const patch: Record<string, unknown> = {
    first_name: firstName,
    last_name: lastName,
    email,
    phone,
    street_address: location,
    address: location,
    property_title: propertyTitle,
    future_pin_label: propertyTitle,
    description,
    pin_writeup: description,
    logo: logoUrl,
    gallery_images: galleryUrls,
    status: "Submitted",
    approval_status: "Pending",
    submitted_at: now,
    requested_account_type: accountType,
    account_type: accountType,
    requested_fast_code: fastCode,
    linked_mapsite_id: mapsiteId,
    assigned_marketing_manager: RAHUL_ASSIGNEE,
    notes,
  };

  if (existing) {
    const { error } = await supabase
      .from("build_requests")
      .update(patch)
      .eq("id", requestId);
    if (error) {
      return { success: false, error: error.message };
    }
  } else {
    const insert: Database["public"]["Tables"]["build_requests"]["Insert"] = {
      id: requestId,
      first_name: firstName,
      last_name: lastName,
      email,
      phone,
      street_address: location,
      address: location,
      property_title: propertyTitle,
      future_pin_label: propertyTitle,
      description,
      pin_writeup: description,
      logo: logoUrl,
      gallery_images: galleryUrls,
      status: "Submitted",
      approval_status: "Pending",
      submitted_at: now,
      requested_account_type: accountType,
      account_type: accountType,
      requested_fast_code: fastCode,
      linked_mapsite_id: mapsiteId,
      assigned_marketing_manager: RAHUL_ASSIGNEE,
      notes,
      company: "",
    };

    const { error } = await supabase.from("build_requests").insert(insert);
    if (error) {
      return { success: false, error: error.message };
    }
  }

  const assetRecord: Database["public"]["Tables"]["mapsite_assets"]["Insert"] = {
    request_id: requestId,
    profile_image: agentPhotoUrl,
    logo_image: logoUrl,
    pin_image: galleryUrls[0] ?? null,
    monologue_pdf: null,
    ebook_pdf: null,
  };

  await supabase.from("mapsite_assets").upsert(assetRecord, {
    onConflict: "request_id",
  });

  if (mapsiteId) {
    await supabase
      .from("mapsites")
      .update({
        assigned_marketing_manager: RAHUL_ASSIGNEE,
        updated_at: now,
      })
      .eq("id", mapsiteId);
  }

  const recipientName = `${firstName} ${lastName}`.trim();
  void sendBuildRequestReceived({
    to: email,
    recipientName,
    requestId,
  });

  const marketingEmails = (process.env.MARKETING_MANAGER_EMAILS || "")
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);

  for (const to of marketingEmails) {
    void sendBuildRequestReceived({
      to,
      recipientName: RAHUL_ASSIGNEE,
      requestId,
    });
  }

  // Automatically generate a Draft TalisBook™ preview from the uploaded images.
  let previewUrl: string | undefined;
  let bookSlug: string | undefined;
  const draftCode =
    fastCode ||
    `rq${requestId.replace(/-/g, "").slice(0, 10).toLowerCase()}`;

  const draft = await autoGenerateDraftTalisBook({
    fastCode: draftCode,
    mapsiteId,
    accountType,
    requestId,
    title: propertyTitle,
    description,
    location,
    images: input.images,
    source: "rahul-assist-teb",
  });

  if (draft.success) {
    previewUrl = draft.previewUrl;
    bookSlug = draft.slug;
    await supabase
      .from("build_requests")
      .update({
        notes: `${notes}\nDraft preview: ${draft.previewUrl}`,
      })
      .eq("id", requestId);
  } else {
    console.warn("[rahul-ebook-assist] Auto-draft skipped:", draft.error);
  }

  return {
    success: true,
    requestId,
    fastCode: fastCode || draftCode,
    previewUrl,
    bookSlug,
  };
}
