import {
  autoGenerateDraftTalisBook,
  type AutoDraftEbookResult,
  type AutoDraftUploadMode,
} from "@/lib/talisbooks/auto-draft-ebook";

export type GenerateSelfServiceEbookInput = {
  fastCode: string;
  mapsiteId?: string | null;
  accountType?: string | null;
  requestId?: string | null;
  title: string;
  description: string;
  location: string;
  images: File[];
  /** `pdf` skips ebook layout rules and renders exact page rasters. */
  uploadMode?: AutoDraftUploadMode;
};

export type GenerateSelfServiceEbookResult =
  | {
      success: true;
      bookId: string;
      slug: string;
      viewerUrl: string;
      mapsiteId: string | null;
    }
  | { success: false; error: string };

/**
 * Client self-service path — delegates to automatic draft generation.
 * Images: fixed 22-page plan — landscapes as continuous facing spreads.
 * PDF: exact page rasters, no Glasshouse / cover scaffolding.
 */
export async function generateSelfServiceEbook(
  input: GenerateSelfServiceEbookInput
): Promise<GenerateSelfServiceEbookResult> {
  const uploadMode = input.uploadMode === "pdf" ? "pdf" : "images";
  const result: AutoDraftEbookResult = await autoGenerateDraftTalisBook({
    fastCode: input.fastCode,
    mapsiteId: input.mapsiteId,
    accountType: input.accountType,
    requestId: input.requestId,
    title: input.title,
    description: input.description,
    location: input.location,
    images: input.images,
    source: uploadMode === "pdf" ? "self-service-pdf" : "self-service-teb",
    uploadMode,
  });

  if (!result.success) {
    return { success: false, error: result.error };
  }

  return {
    success: true,
    bookId: result.bookId,
    slug: result.slug,
    viewerUrl: result.previewUrl,
    mapsiteId: result.mapsiteId,
  };
}
