import {
  autoGenerateDraftTalisBook,
  type AutoDraftEbookResult,
  type AutoDraftUploadMode,
  type OptimizedEbookImageAsset,
} from "@/lib/talisbooks/auto-draft-ebook";
import type {
  SelfServiceBookOptions,
  SelfServicePageCaption,
} from "@/lib/talisbooks/self-service-page-plan";
import type { Rm22TemplatePayload } from "@/lib/talisbooks/rm22-template";
import type { MapsiteFlagIdentity } from "@/lib/talispros/flag-identity";

export type GenerateSelfServiceEbookInput = {
  fastCode: string;
  mapsiteId?: string | null;
  accountType?: string | null;
  requestId?: string | null;
  title: string;
  description: string;
  location: string;
  agentName?: string;
  agentEmail?: string;
  agentPhone?: string;
  brokerageLogo?: File | null;
  agentPhoto?: File | null;
  agentPhotoUrl?: string | null;
  brokerageLogoUrl?: string | null;
  /** Legacy File uploads — prefer `optimizedImages`. */
  images?: File[];
  /** Pre-optimized storage URLs — ebook is built from these only. */
  optimizedImages?: OptimizedEbookImageAsset[];
  /** `pdf` skips ebook layout rules and renders exact page rasters. */
  uploadMode?: AutoDraftUploadMode;
  bookOptions?: Partial<SelfServiceBookOptions>;
  captions?: SelfServicePageCaption[];
  frontCover?: OptimizedEbookImageAsset | null;
  backCover?: OptimizedEbookImageAsset | null;
  rm22Template?: Rm22TemplatePayload | null;
  rm22SlotHydration?: import("@/lib/talisbooks/rm22-template").Rm22SlotHydration | null;
  replaceBookId?: string | null;
  asAdmin?: boolean;
  /** Tag book for catalogue isolated bookshelf (admin-only, not public). */
  isolatedBookshelf?: boolean;
  flagIdentity?: MapsiteFlagIdentity;
};

export type GenerateSelfServiceEbookResult =
  | {
      success: true;
      bookId: string;
      slug: string;
      viewerUrl: string;
      mapsiteId: string | null;
    }
  | { success: false; error: string };

/**
 * Client self-service path — delegates to automatic draft generation.
 * Images: one page plan configured by facingPages / captions / advertising /
 * globalContent / customContent. PDF: exact page rasters.
 */
export async function generateSelfServiceEbook(
  input: GenerateSelfServiceEbookInput
): Promise<GenerateSelfServiceEbookResult> {
  try {
    const uploadMode = input.uploadMode === "pdf" ? "pdf" : "images";
    const result: AutoDraftEbookResult = await autoGenerateDraftTalisBook({
      fastCode: input.fastCode,
      mapsiteId: input.mapsiteId,
      accountType: input.accountType,
      requestId: input.requestId,
      title: input.title,
      description: input.description,
      location: input.location,
      agentName: input.agentName,
      agentEmail: input.agentEmail,
      agentPhone: input.agentPhone,
      brokerageLogo: input.brokerageLogo,
      agentPhoto: input.agentPhoto,
      agentPhotoUrl: input.agentPhotoUrl,
      brokerageLogoUrl: input.brokerageLogoUrl,
      images: input.images,
      optimizedImages: input.optimizedImages,
      source: uploadMode === "pdf" ? "self-service-pdf" : "self-service-teb",
      uploadMode,
      bookOptions: input.bookOptions,
      captions: input.captions,
      frontCover: input.frontCover,
      backCover: input.backCover,
      rm22Template: input.rm22Template,
      rm22SlotHydration: input.rm22SlotHydration,
      replaceBookId: input.replaceBookId,
      asAdmin: input.asAdmin,
      isolatedBookshelf: input.isolatedBookshelf,
      flagIdentity: input.flagIdentity,
    });

    if (!result.success) {
      return { success: false, error: result.error };
    }

    return {
      success: true,
      bookId: result.bookId,
      slug: result.slug,
      viewerUrl: result.previewUrl,
      mapsiteId: result.mapsiteId,
    };
  } catch (error) {
    return {
      success: false,
      error:
        error instanceof Error && error.message.trim()
          ? error.message
          : "Could not generate the Talisbook™.",
    };
  }
}
