import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { mapsiteTalisMapSlug } from "@/lib/talismaps/map-service";

describe("Mapsite™ admin Talismaps™ create", () => {
  it("slugs the Talismaps™ instance from the FAST Code", () => {
    expect(mapsiteTalisMapSlug("LRG1")).toBe("mapsite-lrg1");
    expect(mapsiteTalisMapSlug("  Demo-D1  ")).toBe("mapsite-demo-d1");
  });

  it("uses the Build My Mapsite™ Home PIN flow instead of the backend-team placeholder", () => {
    const editor = readFileSync(
      resolve("components/talispros-admin/MapSiteAdminEditor.tsx"),
      "utf8",
    );
    expect(editor).toContain("HomePinLocationSection");
    expect(editor).toContain("Create Talismaps™");
    expect(editor).not.toContain(
      "Your map link will be generated by Talispros backend team.",
    );
    expect(editor).not.toContain("OpenGraph image");
  });
});
