import { describe, expect, it, vi, beforeEach } from "vitest";
import { generateSelfServiceEbook } from "../lib/talisbooks/self-service-ebook";

vi.mock("../lib/talisbooks/auto-draft-ebook", () => ({
  autoGenerateDraftTalisBook: vi.fn(),
}));

import { autoGenerateDraftTalisBook } from "../lib/talisbooks/auto-draft-ebook";

const generateMock = vi.mocked(autoGenerateDraftTalisBook);

const cover = {
  url: "https://cdn.example/front.jpg",
  width: 1080,
  height: 1920,
};

describe("self-service ebook generate paths", () => {
  beforeEach(() => {
    generateMock.mockReset();
    generateMock.mockResolvedValue({
      success: true,
      bookId: "book-1",
      slug: "ar01-book",
      previewUrl: "/talisbooks/viewer/ar01-book",
      pageCount: 8,
      mapsiteId: "ms-1",
    });
  });

  it("PDF upload mode stays on the exact-page path", async () => {
    const result = await generateSelfServiceEbook({
      fastCode: "ar01",
      title: "PDF book",
      description: "From a PDF",
      location: "Cape Breton",
      optimizedImages: [
        { url: "https://cdn.example/p1.jpg", width: 1920, height: 1080 },
      ],
      frontCover: cover,
      backCover: cover,
      uploadMode: "pdf",
    });

    expect(result.success).toBe(true);
    expect(generateMock).toHaveBeenCalledWith(
      expect.objectContaining({
        source: "self-service-pdf",
        uploadMode: "pdf",
      }),
    );
  });

  it("template / images mode still tags self-service-teb", async () => {
    await generateSelfServiceEbook({
      fastCode: "ar01",
      title: "RM22 book",
      description: "From the template",
      location: "Cape Breton",
      optimizedImages: [
        {
          url: "/talisbooks/templates/rm22/products/g-house.jpg",
          width: 1920,
          height: 1080,
        },
      ],
      frontCover: cover,
      backCover: cover,
      uploadMode: "images",
    });

    expect(generateMock).toHaveBeenCalledWith(
      expect.objectContaining({
        source: "self-service-teb",
        uploadMode: "images",
      }),
    );
  });
});
